import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart';  // Ensure this file is generated by FlutterFire CLI
import 'pages/first_page.dart'; // Import the actual first page file (login or welcome screen)

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Firebase initialization before the app starts
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Initialize Firebase with the correct options
  );
  runApp(MyApp());  // Ensure runApp is called outside Firebase initialization
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Healthcare App', // Optional: Add a title for your app
      theme: ThemeData(
        primarySwatch: Colors.blue, // Optional: Define your theme
      ),
      home: WelcomeScreen(), // Make sure 'WelcomeScreen' exists or replace with correct widget
    );
  }
}
